### ISSUE TITLE
Update IMA types

### ISSUE THREAD

**Issue by jacekbj** [alugha/typed-ima-sdk#1]
Hi,
there has been no update since March 2018. Is there any chance you would be upgrading the lib?

**Comment by jacekbj** [comment]
Forgot to call @niklaskorz

**Comment by niklaskorz** [comment]
We haven't been using the library internally recently, is there any part in particular that has to be updated?

**Comment by jacekbj** [comment]
I wanted to ask about `google.ima.AdsManager.getCurrentAd()`. I checked that it exists in IMA code. However, I am quite surprised by the fact that it does not exist in the documentation: https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManager.

It looks like this issue is invalid. If you happen to know why it's not in the documentation (maybe it shouldn't be used at all) then please let me know. Thanks!

**Comment by jacekbj** [comment]
I misclicked and closed the issue, sorry. Reopening it.

**Comment by jacekbj** [comment]
Another thing is that i.e.
https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED
has actually value `adsManagerLoaded`, not `0` as can be inferred from Enum type. This is true for all Enums.
