### ISSUE TITLE
ima sdk vesrion 

### ISSUE THREAD

**Issue by alyona-mordas** [alugha/typed-ima-sdk#23]
hi guys, 
how can I check which version of ima sdk is used ?

**Comment by niklaskorz** [comment]
The latest version of IMA SDK v3 is loaded directly from Google: https://github.com/alugha/typed-ima-sdk/blob/c863483cf470050fa6c80e640e8e5f6d925b5101/src/loadImaSdk.ts#L10

**Comment by alyona-mordas** [comment]
thank you !
